const images = {
  applogo: require('../assets/images/largeimages/clearchoicelogo.png'),
  drawerlogo: require('../assets/images/largeimages/drawer_logo.png'),
  bbblogo: require('../assets/images/largeimages/bbb-accredited-business.png'),
  certifiedfirmlogo: require('../assets/images/largeimages/iicrc-certified.png'),
  isnlogo: require('../assets/images/largeimages/isnetworld-member.png'),
  loginbg: require('../assets/images/largeimages/loginbg.png'),
  smsicon: require('../assets/images/Icons/sms.png'),
  lockicon: require('../assets/images/Icons/lock.png'),
  down: require('../assets/images/Icons/arrow-down.png'),
  calendar: require('../assets/images/Icons/calendar.png'),
  adminIcon: require('../assets/images/Icons/Admin.png'),
  clock: require('../assets/images/Icons/clock.png'),
  home:require('../assets/images/Icons/home2.png'),
  rightArrow:require('../assets/images/Icons/arrowright.png'),
  aboutuskikos:require('../assets/images/Icons/About_uskikos.png'),
  contactus:require('../assets/images/Icons/contact_usicon.png'),
  ratingicon:require('../assets/images/Icons/rating_icon.png'),
  ratingicon:require('../assets/images/Icons/rating_icon.png'),
  termsandcond:require('../assets/images/Icons/terms_and_cond.png'),
  privacypolicy:require('../assets/images/Icons/privacy_policy.png'),
  logouticon:require('../assets/images/Icons/logout-drawer.png'),

  calandertick:require('../assets/images/Icons/calendar-tick.png'),
  calandertickblack:require('../assets/images/Icons/calendar-tick-black.png'),
  message:require('../assets/images/Icons/msg.png'),
  document:require('../assets/images/Icons/document-text.png'),
  note:require('../assets/images/Icons/note.png'),
  logout:require('../assets/images/Icons/export.png'),
  notification:require('../assets/images/Icons/notification.png'),
  notificationbell:require('../assets/images/Icons/nbell.png'),
  firstline:require('../assets/images/Icons/firstline.png'),
  profileservice:require('../assets/images/Icons/services.png'),
  profileservicelog:require('../assets/images/Icons/servicelog.png'),
  smsgray:require('../assets/images/Icons/smsgray.png'),
  callgray:require('../assets/images/Icons/callgray.png'), 
  adminicon:require('../assets/images/Icons/adminicon.png'),
  gallaryicon: require('../assets/images/Icons/gallery_4x_white.png'),
  gallaryvideoicon: require('../assets/images/Icons/video-play_4xWhite.png'),
 redNotifications:require('../assets/images/Icons/rednotification.png'),
  splash: require('../assets/images/largeimages/splash.png'),
  loginlogo: require('../assets/images/largeimages/loginlogo.png'),
  arrowleft:require('../assets/images/Icons/arrow-left.png'),
  successimg:require('../assets/images/Icons/successimg.png'),
  loginneddimg:require('../assets/images/Icons/NeedAcount.png'),
  eye:require('../assets/images/Icons/eye.png'),
  ceye:require('../assets/images/Icons/eye-slash.png'),
  fillter: require('../assets/images/Icons/filter-square.png'),
  groupImg:require('../assets/images/largeimages/g10.png'),
  img2img:require('../assets/images/largeimages/Group3img.png'),
img3img:require('../assets/images/largeimages/Profile3boximg.png'),
smileyemoji:require('../assets/images/Icons/SmileyEmoji.png'),

  frame:require('../assets/images/largeimages/Frame.png'),
  ellipse:require('../assets/images/Icons/Ellipse16.png'),
  callicon:require('../assets/images/Icons/Vector.png'),
  location:require('../assets/images/Icons/location.png'),
  document:require('../assets/images/Icons/document-copy.png'),
  videoIcon:require('../assets/images/Icons/video-play.png'),
  arrowsRight:require('../assets/images/Icons/arrowsRight.png')
  
};
export default images;
